In [1]:
import numpy as np

In [20]:
a=np.array([1,2,3,4,5,6,7,8,9,10])


In [21]:
a.sum()

55

In [22]:
a.mean()


5.5

In [23]:
a.max()

10

In [24]:
a.min()

1

In [25]:
fifth_day_sales=a[4]
fifth_day_sales

5

In [26]:
first_five=a[:5]
last_five=a[len(a)-5:]
print(first_five)
print(last_five)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [27]:
increased_sale=a+10
increased_sale

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
total_sales=a.sum()
total_sales

55

In [30]:
a.mean()

5.5

In [32]:
max_sales=a.max()
max_sales

10

min_sales=a.min()
min_sales

In [35]:
min_sales=a.min() 
min_sales

1

In [36]:
reshaped_matrix=a.reshape(2,5)
reshaped_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
li=np.sum(reshaped_matrix,axis=1)
li

array([15, 40])

In [44]:
p,q=li  #

In [45]:
q

40

In [48]:
p

15

In [49]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
high_sales_days=a>4
high_sales_days

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
b=np.array([0,1,1,2,3,3,2,2,2,5])

In [53]:
c=a-b
c

array([1, 1, 2, 2, 2, 3, 5, 6, 7, 5])