In [1]:
#Numpy_assignment
#Accept 20 numbers from user an store them in 4(5 numbers in each list
#Convert lists into 2 numpy array(list1,list2 in array1 and list3 and list4 in array2)

In [3]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
c=[11,12,13,14,15]
d=[16,17,18,19,20]

In [19]:
import numpy as np
arr=np.array(a+b)
arr
arr1=np.array(c+d)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
a = arr+arr1
a

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [20]:
np.add(arr,arr1)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [21]:
np.subtract(arr1,arr)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [29]:
a = arr1-arr
a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [24]:
np.multiply(arr,arr1)

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [30]:
a = arr*arr1
a

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [18]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [32]:
a = arr1**arr
a

array([         11,         144,        2197,       38416,      759375,
          16777216,   410338673, -1864941312,   565150579,   797966336],
      dtype=int32)

Time Series

In [34]:
import pandas as pd
import numpy as np

In [38]:
#create a date range
dates=pd.date_range(start='2024-01-01',periods=10, freq='D') #D show sdaily H shows hourly
print(dates.dtype,dates,"\n")

datetime64[ns] DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D') 



In [41]:
#create a time series with random data
data=np.random.randn(10)
time_series=pd.Series(data,index=dates)
time_series

2024-01-01    1.312103
2024-01-02   -0.009620
2024-01-03    1.538204
2024-01-04   -0.484571
2024-01-05    0.290818
2024-01-06   -0.264577
2024-01-07   -1.063359
2024-01-08   -1.089200
2024-01-09   -0.740297
2024-01-10   -1.214817
Freq: D, dtype: float64

In [44]:
time_series['2024-01-05']

0.29081759332026746

In [46]:
time_series['2024-01-03':'2024-01-06']

2024-01-03    1.538204
2024-01-04   -0.484571
2024-01-05    0.290818
2024-01-06   -0.264577
Freq: D, dtype: float64

In [48]:
time_series[time_series>0]

2024-01-01    1.312103
2024-01-03    1.538204
2024-01-05    0.290818
dtype: float64

In [50]:
hourly_dates=pd.date_range('2024-01-01',periods=24,freq='h')
hourly_data=np.random.randn(24)
hourly_series=pd.Series(hourly_data,index=hourly_dates)
hourly_series

2024-01-01 00:00:00    1.249967
2024-01-01 01:00:00   -1.791846
2024-01-01 02:00:00   -0.644740
2024-01-01 03:00:00    0.333930
2024-01-01 04:00:00   -1.667775
2024-01-01 05:00:00    1.399499
2024-01-01 06:00:00   -0.036524
2024-01-01 07:00:00   -0.908342
2024-01-01 08:00:00   -0.727994
2024-01-01 09:00:00   -0.273892
2024-01-01 10:00:00    0.038014
2024-01-01 11:00:00    0.413666
2024-01-01 12:00:00   -1.890974
2024-01-01 13:00:00   -0.605952
2024-01-01 14:00:00   -0.821246
2024-01-01 15:00:00   -0.549241
2024-01-01 16:00:00    1.114475
2024-01-01 17:00:00    1.197498
2024-01-01 18:00:00   -0.668629
2024-01-01 19:00:00   -0.573405
2024-01-01 20:00:00   -0.395948
2024-01-01 21:00:00    2.059898
2024-01-01 22:00:00    0.103421
2024-01-01 23:00:00    0.631891
Freq: H, dtype: float64

In [53]:
hourly_series['2024-01-01 15:00']

-0.5492407629145086

In [67]:
time_series['2024-01-01':'2024-01-10'][time_series>0]

2024-01-01    1.312103
2024-01-03    1.538204
2024-01-05    0.290818
dtype: float64

In [57]:
time_series.loc['2024-01-05']

0.29081759332026746

In [59]:
time_series.loc['2024-01-03':'2024-01-06']

2024-01-03    1.538204
2024-01-04   -0.484571
2024-01-05    0.290818
2024-01-06   -0.264577
Freq: D, dtype: float64

In [62]:
time_series.loc[['2024-01-01','2024-01-03','2024-01-05']]

2024-01-01    1.312103
2024-01-03    1.538204
2024-01-05    0.290818
dtype: float64

In [64]:
time_series.iloc[0]

1.3121025663597286

In [66]:
time_series.iloc[2:6]

2024-01-03    1.538204
2024-01-04   -0.484571
2024-01-05    0.290818
2024-01-06   -0.264577
Freq: D, dtype: float64

In [73]:
time_series.iloc[[0,3,7]]

2024-01-01    1.312103
2024-01-04   -0.484571
2024-01-08   -1.089200
dtype: float64

In [75]:
#access date before a date"
print(time_series[:'2024-01-05'])

2024-01-01    1.312103
2024-01-02   -0.009620
2024-01-03    1.538204
2024-01-04   -0.484571
2024-01-05    0.290818
Freq: D, dtype: float64


In [77]:
#access data after a specfic date
print(time_series['2024-01-06':])

2024-01-06   -0.264577
2024-01-07   -1.063359
2024-01-08   -1.089200
2024-01-09   -0.740297
2024-01-10   -1.214817
Freq: D, dtype: float64


In [80]:
#resampling

weekly_series=time_series.resample('W').mean()
weekly_series

2024-01-07    0.188428
2024-01-14   -1.014771
Freq: W-SUN, dtype: float64

In [84]:
rolling_mean=time_series.rolling(window=3).mean()
rolling_mean

2024-01-01         NaN
2024-01-02         NaN
2024-01-03    0.946896
2024-01-04    0.348005
2024-01-05    0.448150
2024-01-06   -0.152777
2024-01-07   -0.345706
2024-01-08   -0.805712
2024-01-09   -0.964286
2024-01-10   -1.014771
Freq: D, dtype: float64

In [90]:
time_series['2024-01-04']=np.nan
filled_series=time_series.ffill()
weekly_series=time_series.resample('W').mean()
weekly_series

2024-01-07    0.300595
2024-01-14   -1.014771
Freq: W-SUN, dtype: float64

In [92]:
filled_backward=time_series.bfill()
filled_backward

2024-01-01    1.312103
2024-01-02   -0.009620
2024-01-03    1.538204
2024-01-04    0.290818
2024-01-05    0.290818
2024-01-06   -0.264577
2024-01-07   -1.063359
2024-01-08   -1.089200
2024-01-09   -0.740297
2024-01-10   -1.214817
Freq: D, dtype: float64

In [95]:
interpolated=time_series.interpolate()
interpolated

2024-01-01    1.312103
2024-01-02   -0.009620
2024-01-03    1.538204
2024-01-04    0.914511
2024-01-05    0.290818
2024-01-06   -0.264577
2024-01-07   -1.063359
2024-01-08   -1.089200
2024-01-09   -0.740297
2024-01-10   -1.214817
Freq: D, dtype: float64

In [99]:
dates=pd.date_range(start="2024-01-01",periods=10,freq="D")
dates

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

In [104]:
data=[1,2,np.nan,4,np.nan,6,7,np.nan,9,10]
time_series=pd.Series(data,index=dates)
time_series

2024-01-01     1.0
2024-01-02     2.0
2024-01-03     NaN
2024-01-04     4.0
2024-01-05     NaN
2024-01-06     6.0
2024-01-07     7.0
2024-01-08     NaN
2024-01-09     9.0
2024-01-10    10.0
Freq: D, dtype: float64

In [107]:
missing_values=time_series.isna()
missing_values

2024-01-01    False
2024-01-02    False
2024-01-03     True
2024-01-04    False
2024-01-05     True
2024-01-06    False
2024-01-07    False
2024-01-08     True
2024-01-09    False
2024-01-10    False
Freq: D, dtype: bool

In [111]:
num_missing=missing_values.sum()
num_missing

3

In [113]:
missing_indices=time_series.index[missing_values]
missing_indices

DatetimeIndex(['2024-01-03', '2024-01-05', '2024-01-08'], dtype='datetime64[ns]', freq=None)

In [115]:
filled_value=time_series.fillna(0)
filled_value

2024-01-01     1.0
2024-01-02     2.0
2024-01-03     0.0
2024-01-04     4.0
2024-01-05     0.0
2024-01-06     6.0
2024-01-07     7.0
2024-01-08     0.0
2024-01-09     9.0
2024-01-10    10.0
Freq: D, dtype: float64

In [118]:
dropped=time_series.dropna()
dropped

2024-01-01     1.0
2024-01-02     2.0
2024-01-04     4.0
2024-01-06     6.0
2024-01-07     7.0
2024-01-09     9.0
2024-01-10    10.0
dtype: float64

In [120]:
weekly_series

2024-01-07    0.300595
2024-01-14   -1.014771
Freq: W-SUN, dtype: float64

In [123]:
dates=pd.date_range(start="2024-01-01",periods=10,freq='D')
data=np.arange(10)
time_series=pd.Series(data,index=dates)
time_series

2024-01-01    0
2024-01-02    1
2024-01-03    2
2024-01-04    3
2024-01-05    4
2024-01-06    5
2024-01-07    6
2024-01-08    7
2024-01-09    8
2024-01-10    9
Freq: D, dtype: int32

In [128]:
shifted_forward=time_series.shift(2)
shifted_forward

2024-01-01    NaN
2024-01-02    NaN
2024-01-03    0.0
2024-01-04    1.0
2024-01-05    2.0
2024-01-06    3.0
2024-01-07    4.0
2024-01-08    5.0
2024-01-09    6.0
2024-01-10    7.0
Freq: D, dtype: float64

In [131]:
shifted_backward=time_series.shift(-2)
shifted_backward

2024-01-01    2.0
2024-01-02    3.0
2024-01-03    4.0
2024-01-04    5.0
2024-01-05    6.0
2024-01-06    7.0
2024-01-07    8.0
2024-01-08    9.0
2024-01-09    NaN
2024-01-10    NaN
Freq: D, dtype: float64

shifted_forward_filled=time_series.shift(2).fillna(0)
shifted_forward_filled

In [163]:
#analyzing and forecasting stock exchange data
import pandas as pd
df=pd.read_csv("A.csv")
df.head()
df['Date']=pd.to_datetime(df['Date'])
df.set_index('Date',inplace=True)
df


Open       High        Low      Close  \
Date                                                                        
1970-01-01 00:00:00.000000032        NaN  35.765381  28.612303  31.473534   
1970-01-01 00:00:00.000000030  30.758226  28.478184  28.880543  24.838577   
1970-01-01 00:00:00.000000029  31.473534  28.657009  31.473534  27.068665   
1970-01-01 00:00:00.000000030  31.205294  28.612303  28.612303  24.607880   
1970-01-01 00:00:00.000000028  29.998211  28.612303  29.372318  25.261524   
...                                  ...        ...        ...        ...   
1970-01-01 00:00:00.000000070  74.449997  69.650002  73.720001  73.532867   
1970-01-01 00:00:00.000000071  73.209999  70.279999  70.910004  70.730003   
1970-01-01 00:00:00.000000071  73.180000  71.059998  72.669998  72.669998   
1970-01-01 00:00:00.000000072  72.800003  70.500000  71.620003  71.620003   
1970-01-01 00:00:00.000000069  70.230003  68.150002  68.919998  68.919998   

                                  Adj Close      Volume  
Date                                                     
1970-01-01 00:00:00.000000032  2.706866e+01  62546300.0  
1970-01-01 00:00:00.000000030  1.523410e+07         NaN  
1970-01-01 00:00:00.000000029  6.577800e+06         NaN  
1970-01-01 00:00:00.000000030  5.975600e+06         NaN  
1970-01-01 00:00:00.000000028  4.843200e+06         NaN  
...                                     ...         ...  
1970-01-01 00:00:00.000000070  3.267500e+06         NaN  
1970-01-01 00:00:00.000000071  1.829800e+06         NaN  
1970-01-01 00:00:00.000000071  1.486200e+06         NaN  
1970-01-01 00:00:00.000000072  1.822100e+06         NaN  
1970-01-01 00:00:00.000000069  2.173600e+06         NaN  

[5124 rows x 6 columns]

In [164]:
df.isna().sum()

Open            1
High            0
Low             0
Close           0
Adj Close       0
Volume       5123
dtype: int64

In [169]:
df.bfill()


Open       High        Low      Close  \
Date                                                                        
1970-01-01 00:00:00.000000032  30.758226  35.765381  28.612303  31.473534   
1970-01-01 00:00:00.000000030  30.758226  28.478184  28.880543  24.838577   
1970-01-01 00:00:00.000000029  31.473534  28.657009  31.473534  27.068665   
1970-01-01 00:00:00.000000030  31.205294  28.612303  28.612303  24.607880   
1970-01-01 00:00:00.000000028  29.998211  28.612303  29.372318  25.261524   
...                                  ...        ...        ...        ...   
1970-01-01 00:00:00.000000070  74.449997  69.650002  73.720001  73.532867   
1970-01-01 00:00:00.000000071  73.209999  70.279999  70.910004  70.730003   
1970-01-01 00:00:00.000000071  73.180000  71.059998  72.669998  72.669998   
1970-01-01 00:00:00.000000072  72.800003  70.500000  71.620003  71.620003   
1970-01-01 00:00:00.000000069  70.230003  68.150002  68.919998  68.919998   

                                  Adj Close      Volume  
Date                                                     
1970-01-01 00:00:00.000000032  2.706866e+01  62546300.0  
1970-01-01 00:00:00.000000030  1.523410e+07         NaN  
1970-01-01 00:00:00.000000029  6.577800e+06         NaN  
1970-01-01 00:00:00.000000030  5.975600e+06         NaN  
1970-01-01 00:00:00.000000028  4.843200e+06         NaN  
...                                     ...         ...  
1970-01-01 00:00:00.000000070  3.267500e+06         NaN  
1970-01-01 00:00:00.000000071  1.829800e+06         NaN  
1970-01-01 00:00:00.000000071  1.486200e+06         NaN  
1970-01-01 00:00:00.000000072  1.822100e+06         NaN  
1970-01-01 00:00:00.000000069  2.173600e+06         NaN  

[5124 rows x 6 columns]

In [172]:
df.interpolate()

Open       High        Low      Close  \
Date                                                                        
1970-01-01 00:00:00.000000032        NaN  35.765381  28.612303  31.473534   
1970-01-01 00:00:00.000000030  30.758226  28.478184  28.880543  24.838577   
1970-01-01 00:00:00.000000029  31.473534  28.657009  31.473534  27.068665   
1970-01-01 00:00:00.000000030  31.205294  28.612303  28.612303  24.607880   
1970-01-01 00:00:00.000000028  29.998211  28.612303  29.372318  25.261524   
...                                  ...        ...        ...        ...   
1970-01-01 00:00:00.000000070  74.449997  69.650002  73.720001  73.532867   
1970-01-01 00:00:00.000000071  73.209999  70.279999  70.910004  70.730003   
1970-01-01 00:00:00.000000071  73.180000  71.059998  72.669998  72.669998   
1970-01-01 00:00:00.000000072  72.800003  70.500000  71.620003  71.620003   
1970-01-01 00:00:00.000000069  70.230003  68.150002  68.919998  68.919998   

                                  Adj Close      Volume  
Date                                                     
1970-01-01 00:00:00.000000032  2.706866e+01  62546300.0  
1970-01-01 00:00:00.000000030  1.523410e+07  62546300.0  
1970-01-01 00:00:00.000000029  6.577800e+06  62546300.0  
1970-01-01 00:00:00.000000030  5.975600e+06  62546300.0  
1970-01-01 00:00:00.000000028  4.843200e+06  62546300.0  
...                                     ...         ...  
1970-01-01 00:00:00.000000070  3.267500e+06  62546300.0  
1970-01-01 00:00:00.000000071  1.829800e+06  62546300.0  
1970-01-01 00:00:00.000000071  1.486200e+06  62546300.0  
1970-01-01 00:00:00.000000072  1.822100e+06  62546300.0  
1970-01-01 00:00:00.000000069  2.173600e+06  62546300.0  

[5124 rows x 6 columns]